# RETAIL REVENUE INTELLIGENCE & PROFITABILITY OPTIMIZATION
# PHASE 2: DATA CLEANING & FEATURE ENGINEERING

## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:,.2f}".format)

## 2. Load Dataset

In [2]:
df = pd.read_csv("Superstore.csv", encoding="latin1")

print("Dataset loaded successfully.")
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

df.head()

Dataset loaded successfully.
Rows: 9994
Columns: 21

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.00,41.91
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.00,219.58
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.00,6.87
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.58,5,0.45,-383.03
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.37,2,0.20,2.52

## 3. Standardize Column Names

In [3]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

print("Standardized columns:")
print(df.columns.tolist())

Standardized columns:
['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit']

## 4. Initial Data Inspection

In [4]:
print("Dataset Shape:")
print(df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nDataset Info:")
df.info()

print("\nSummary Statistics:")
display(df.describe(include="all"))

Dataset Shape:
(9994, 21)

Data Types:
row_id             int64
order_id          object
order_date        object
ship_date         object
ship_mode         object
customer_id       object
customer_name     object
segment           object
country           object
city              object
state             object
postal_code        int64
region            object
product_id        object
category          object
sub_category      object
product_name      object
sales            float64
quantity           int64
discount         float64
profit           float64
dtype: object

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   int64
 1   order_id       9994 non-null   object
 2   order_date     9994 non-null   object
 3   ship_date      9994 non-null   object
 4   ship_mode      9994 non-null   object
 5   customer_id    9994 non-null   object
 6   customer_name  9994 non-null   object
 7   segment        9994 non-null   object
 8   country        9994 non-null   object
 9   city           9994 non-null   object
 10  state          9994 non-null   object
 11  postal_code    9994 non-null   int64
 12  region         9994 non-null   object
 13  product_id     9994 non-null   object
 14  category       9994 non-null   object
 15  sub_category   9994 non-null   object
 16  product_name   9994 non-null   object
 17  sales          9994 non-null   float64
 18  quantity       9994 non-null   int64
 19  discount       9994 non-null   float64
 20  profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

Summary Statistics:

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,state,postal_code,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit
count,"9,994.00",9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,"9,994.00",9994,9994,9994,9994,9994,"9,994.00","9,994.00","9,994.00","9,994.00"
unique,NaN,5009,1237,1334,4,793,793,3,1,531,49,NaN,4,1862,3,17,1850,NaN,NaN,NaN,NaN
top,NaN,CA-2017-100111,9/5/2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,NaN,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,NaN,NaN,NaN,NaN
freq,NaN,14,38,35,5968,37,37,5191,9994,915,2001,NaN,3203,19,6026,1523,48,NaN,NaN,NaN,NaN
mean,"4,997.50",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"55,190.38",NaN,NaN,NaN,NaN,NaN,229.86,3.79,0.16,28.66
std,"2,885.16",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"32,063.69",NaN,NaN,NaN,NaN,NaN,623.25,2.23,0.21,234.26
min,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,040.00",NaN,NaN,NaN,NaN,NaN,0.44,1.00,0.00,"-6,599.98"
25%,"2,499.25",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"23,223.00",NaN,NaN,NaN,NaN,NaN,17.28,2.00,0.00,1.73
50%,"4,997.50",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"56,430.50",NaN,NaN,NaN,NaN,NaN,54.49,3.00,0.20,8.67
75%,"7,495.75",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"90,008.00",NaN,NaN,NaN,NaN,NaN,209.94,5.00,0.20,29.36
max,"9,994.00",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"99,301.00",NaN,NaN,NaN,NaN,NaN,"22,638.48",14.00,0.80,"8,399.98"

## 5. Missing Value Analysis

In [5]:
missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (df.isnull().sum() / len(df)) * 100
}).sort_values(by="missing_count", ascending=False)

display(missing_summary)

               missing_count  missing_percentage
row_id                     0                0.00
order_id                   0                0.00
order_date                 0                0.00
ship_date                  0                0.00
ship_mode                  0                0.00
customer_id                0                0.00
customer_name              0                0.00
segment                    0                0.00
country                    0                0.00
city                       0                0.00
state                      0                0.00
postal_code                0                0.00
region                     0                0.00
product_id                 0                0.00
category                   0                0.00
sub_category               0                0.00
product_name               0                0.00
sales                      0                0.00
quantity                   0                0.00
discount                   0                0.00
profit                     0                0.00

## 6. Duplicate Analysis

In [6]:
total_duplicates = df.duplicated().sum()
print(f"Total duplicate rows: {total_duplicates}")

if total_duplicates > 0:
    df = df.drop_duplicates()
    print("Duplicate rows removed.")
else:
    print("No duplicate rows found.")

Total duplicate rows: 0
No duplicate rows found.

## 7. Data Type Correction

In [7]:
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["ship_date"] = pd.to_datetime(df["ship_date"], errors="coerce")

numeric_columns = ["sales", "quantity", "discount", "profit"]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("Corrected data types:")
print(df.dtypes)

Corrected data types:
row_id                    int64
order_id                 object
order_date       datetime64[ns]
ship_date        datetime64[ns]
ship_mode                object
customer_id              object
customer_name            object
segment                  object
country                  object
city                     object
state                    object
postal_code               int64
region                   object
product_id               object
category                 object
sub_category             object
product_name             object
sales                   float64
quantity                  int64
discount                float64
profit                  float64
dtype: object

## 8. Date Quality Validation

In [8]:
invalid_order_dates = df["order_date"].isnull().sum()
invalid_ship_dates = df["ship_date"].isnull().sum()

print(f"Invalid order dates: {invalid_order_dates}")
print(f"Invalid ship dates: {invalid_ship_dates}")

df["shipping_days"] = (df["ship_date"] - df["order_date"]).dt.days

invalid_shipping_days = df[df["shipping_days"] < 0]

print(f"Rows with negative shipping days: {len(invalid_shipping_days)}")

Invalid order dates: 0
Invalid ship dates: 0
Rows with negative shipping days: 0

## 9. Business Logic Validation

In [9]:
print("Negative sales records:", len(df[df["sales"] < 0]))
print("Negative quantity records:", len(df[df["quantity"] < 0]))
print("Discount below 0:", len(df[df["discount"] < 0]))
print("Discount above 1:", len(df[df["discount"] > 1]))

print("Loss-making transactions:", len(df[df["profit"] < 0]))
print("Zero-profit transactions:", len(df[df["profit"] == 0]))
print("Profitable transactions:", len(df[df["profit"] > 0]))

Negative sales records: 0
Negative quantity records: 0
Discount below 0: 0
Discount above 1: 0
Loss-making transactions: 1871
Zero-profit transactions: 65
Profitable transactions: 8058

## 10. Remove Invalid Business Records If Any

In [10]:
df = df[df["sales"] >= 0]
df = df[df["quantity"] >= 0]
df = df[(df["discount"] >= 0) & (df["discount"] <= 1)]
df = df[df["shipping_days"] >= 0]

print("Dataset shape after business validation:")
print(df.shape)

Dataset shape after business validation:
(9994, 22)

## 11. Feature Engineering: Date Features

In [11]:
df["order_year"] = df["order_date"].dt.year
df["order_month"] = df["order_date"].dt.month
df["order_month_name"] = df["order_date"].dt.month_name()
df["order_quarter"] = df["order_date"].dt.quarter
df["order_year_month"] = df["order_date"].dt.to_period("M").astype(str)
df["order_day_of_week"] = df["order_date"].dt.day_name()

## 12. Feature Engineering: Profitability Metrics

In [12]:
df["profit_margin"] = np.where(
    df["sales"] != 0,
    df["profit"] / df["sales"],
    0
)

df["profit_margin_percentage"] = df["profit_margin"] * 100

df["loss_making_flag"] = np.where(df["profit"] < 0, 1, 0)

df["profitability_status"] = np.select(
    [
        df["profit"] < 0,
        df["profit"] == 0,
        df["profit"] > 0
    ],
    [
        "Loss Making",
        "Break Even",
        "Profitable"
    ],
    default="Unknown"
)

## 13. Feature Engineering: Discount Segmentation

In [13]:
df["discount_band"] = pd.cut(
    df["discount"],
    bins=[-0.01, 0, 0.10, 0.20, 0.40, 1.00],
    labels=[
        "No Discount",
        "Low Discount",
        "Moderate Discount",
        "High Discount",
        "Extreme Discount"
    ]
)

## 14. Feature Engineering: Revenue Segmentation

In [14]:
df["revenue_category"] = pd.qcut(
    df["sales"],
    q=4,
    labels=[
        "Low Revenue",
        "Medium Revenue",
        "High Revenue",
        "Premium Revenue"
    ]
)

## 15. Feature Engineering: Shipping Performance

In [15]:
df["shipping_speed"] = np.select(
    [
        df["shipping_days"] <= 2,
        df["shipping_days"].between(3, 5),
        df["shipping_days"] > 5
    ],
    [
        "Fast",
        "Standard",
        "Delayed"
    ],
    default="Unknown"
)

## 16. Feature Engineering: Customer Profitability

In [16]:
customer_profitability = (
    df.groupby("customer_id")
    .agg(
        customer_total_sales=("sales", "sum"),
        customer_total_profit=("profit", "sum"),
        customer_order_count=("order_id", "nunique")
    )
    .reset_index()
)

customer_profitability["customer_profit_margin"] = np.where(
    customer_profitability["customer_total_sales"] != 0,
    customer_profitability["customer_total_profit"] / customer_profitability["customer_total_sales"],
    0
)

customer_profitability["customer_segment_risk"] = np.select(
    [
        customer_profitability["customer_total_sales"] >= customer_profitability["customer_total_sales"].quantile(0.75),
        customer_profitability["customer_total_profit"] < 0,
        customer_profitability["customer_profit_margin"] < 0.05
    ],
    [
        "High Value Customer",
        "Loss Making Customer",
        "Low Margin Customer"
    ],
    default="Standard Customer"
)

df = df.merge(
    customer_profitability[
        [
            "customer_id",
            "customer_total_sales",
            "customer_total_profit",
            "customer_order_count",
            "customer_profit_margin",
            "customer_segment_risk"
        ]
    ],
    on="customer_id",
    how="left"
)

## 17. Outlier Analysis

In [17]:
def detect_outliers_iqr(dataframe, column):
    q1 = dataframe[column].quantile(0.25)
    q3 = dataframe[column].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = dataframe[
        (dataframe[column] < lower_bound) |
        (dataframe[column] > upper_bound)
    ]

    return lower_bound, upper_bound, len(outliers)

outlier_columns = ["sales", "quantity", "discount", "profit", "shipping_days"]

outlier_summary = []

for col in outlier_columns:
    lower, upper, count = detect_outliers_iqr(df, col)
    outlier_summary.append({
        "column": col,
        "lower_bound": lower,
        "upper_bound": upper,
        "outlier_count": count,
        "outlier_percentage": (count / len(df)) * 100
    })

outlier_summary_df = pd.DataFrame(outlier_summary)
display(outlier_summary_df)

          column  lower_bound  upper_bound  outlier_count  outlier_percentage
0          sales      -271.71       498.93           1167               11.68
1       quantity        -2.50         9.50            170                1.70
2       discount        -0.30         0.50            856                8.57
3         profit       -39.72        70.82           1881               18.82
4  shipping_days         0.00         8.00              0                0.00

## 19. Final Quality Check

In [18]:
final_quality_check = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": (df.isnull().sum() / len(df)) * 100,
    "data_type": df.dtypes
})

display(final_quality_check)

print("Final dataset shape:")
print(df.shape)

print("Final columns:")
print(df.columns.tolist())

                          missing_count  missing_percentage       data_type
row_id                                0                0.00           int64
order_id                              0                0.00          object
order_date                            0                0.00  datetime64[ns]
ship_date                             0                0.00  datetime64[ns]
ship_mode                             0                0.00          object
customer_id                           0                0.00          object
customer_name                         0                0.00          object
segment                               0                0.00          object
country                               0                0.00          object
city                                  0                0.00          object
state                                 0                0.00          object
postal_code                           0                0.00           int64
region                                0                0.00          object
product_id                            0                0.00          object
category                              0                0.00          object
sub_category                          0                0.00          object
product_name                          0                0.00          object
sales                                 0                0.00         float64
quantity                              0                0.00           int64
discount                              0                0.00         float64
profit                                0                0.00         float64
shipping_days                         0                0.00           int64
order_year                            0                0.00           int32
order_month                           0                0.00           int32
order_month_name                      0                0.00          object
order_quarter                         0                0.00           int32
order_year_month                      0                0.00          object
order_day_of_week                     0                0.00          object
profit_margin                         0                0.00         float64
profit_margin_percentage              0                0.00         float64
loss_making_flag                      0                0.00           int64
profitability_status                  0                0.00          object
discount_band                         0                0.00        category
revenue_category                      0                0.00        category
shipping_speed                        0                0.00          object
customer_total_sales                  0                0.00         float64
customer_total_profit                 0                0.00         float64
customer_order_count                  0                0.00           int64
customer_profit_margin                0                0.00         float64
customer_segment_risk                 0                0.00          object

Final dataset shape:
(9994, 40)
Final columns:
['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit', 'shipping_days', 'order_year', 'order_month', 'order_month_name', 'order_quarter', 'order_year_month', 'order_day_of_week', 'profit_margin', 'profit_margin_percentage', 'loss_making_flag', 'profitability_status', 'discount_band', 'revenue_category', 'shipping_speed', 'customer_total_sales', 'customer_total_profit', 'customer_order_count', 'customer_profit_margin', 'customer_segment_risk']

## 20. Export Cleaned Dataset

In [19]:
df.to_csv("superstore_cleaned.csv", index=False)

print("Cleaned dataset exported successfully as superstore_cleaned.csv")

Cleaned dataset exported successfully as superstore_cleaned.csv